### ISSUE TITLE
wrong background-size when using keyframe-animations

### ISSUE THREAD

**Issue by g12n** [LeaVerou/conic-gradient#9] opened 2015-06-29 13:18 UTC
I tried to use the conical gradient in combination with a keyframe animation. 
The Size of the Background-Tile isn't anymore covering the html-element. 

I posted a sample code on Codepen: http://codepen.io/g12n/pen/BNJVYa
- three tiles with the steps of the animation
- a fourth one with the animated background 

I tested this on Chrome Version 43.0.2357.130 (64-bit), OS X 10.9.5: 

![20150629-150657_capture](https://cloud.githubusercontent.com/assets/57556/8408506/f681347e-1e70-11e5-81ff-80170cedb406.gif)

**Comment by LeaVerou** [comment] 2015-08-15 17:16
This looks more like a Chrome bug than a bug of the polyfill…

**Comment by kumarharsh** [comment] 2015-08-15 22:03
I've encountered similar issues with linear-gradient on _some_ chrome builds. Specifically, non-scaling of background-image() even when the background-size and background-repeat are specified correctly.
I presume it's a blink bug, although I can't reproduce it now. Just happened like on one particular computer everyday -_-.

**Comment by g12n** [comment] 2015-11-02 10:59
OK, I guess we can close that one and hope for chrome to catch up.

**Comment by kumarharsh** [comment] 2015-11-02 11:04
Keep it open and raise an issue on Chrome's tracker.
Maybe its a collusion of both the browser and the library which is breaking that gradient.

**Comment by tregusti** [comment] 2016-02-22 15:35
Could you please provide a link to the issue in Chromiums tracker?

**Comment by g12n** [comment] 2016-04-02 15:22
I actually haven't got to formulate a Bug report yet. Sorry! I wouldn't even be sure, what the bug actually is. Maybe you can point me into the right direction.

**Comment by eonj** [comment] 2016-12-23 02:01
@g12n I testesd your codepen sample with Chrome 55.0.2883.91 and it was a Chrome bug fixed now. Can you test it again?

**Closed as completed** 2020-06-10 08:46 UTC
